name = "praxis-ai-backend"
main = "src/app.ts"
compatibility_date = "2024-12-18"

[env.production]
name = "praxis-ai-backend-prod"

[env.staging]
name = "praxis-ai-backend-staging"

[[env.production.vars]]
SUPABASE_URL = "your-production-supabase-url"
SUPABASE_ANON_KEY = "your-production-supabase-anon-key"
OPENAI_API_KEY = "your-openai-api-key"
ANTHROPIC_API_KEY = "your-anthropic-api-key"

[[env.staging.vars]]
SUPABASE_URL = "your-staging-supabase-url"
SUPABASE_ANON_KEY = "your-staging-supabase-anon-key"
OPENAI_API_KEY = "your-openai-api-key"
ANTHROPIC_API_KEY = "your-anthropic-api-key"
